version: '2.2'
services:
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      #- cluster.initial_master_nodes=es02
      - "ES_JAVA_OPTS=-Xms7g -Xmx7g"
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  kib02:
    image: docker.elastic.co/kibana/kibana:7.15.2
    container_name: kib02
    depends_on: 
      - es02
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es02:9200
      ELASTICSEARCH_HOSTS: '["http://es02:9200"]'
    networks:
      - elastic

volumes:
  data01:
    driver: local

networks:
  elastic:
    driver: bridge
